### ISSUE TITLE
Depend on openjdk rather than jre8

### ISSUE THREAD

**Issue by brianary** [leiningen/leiningen-chocolatey#5]
I'm not sure why version 8 specifically is necessary, but if OpenJDK 11 is viable, the licensing considerations for that are [less onerous than for Oracle's](https://www.itassetmanagement.net/2018/05/01/oracle-to-charge-for-java-from-jan-2019/).

**Comment by winks** [comment]
Thanks, we kinda put that into effect when 11 was not yet released (iirc) and 10 was really finicky with Clojure.
Will investigate and hopefully be able to change that for the next release.

**Comment by winks** [comment]
@brianary I've just uploaded this to Chocolatey, would be cool if you could give it a try - I'm developing this on Win7 and everything has a little bit of guesswork involved (due to TLS 1.3 downloads on github) :(

It's unlisted (for a few days usually) so maybe https://chocolatey.org/packages/Lein/2.9.0 works, otherwise let's see if it's approved.

**Comment by brianary** [comment]
`cinst lein --version=2.9.0 -y` seems to work. I'll have to try from home to be sure, but I think it looks good.
